services:
  kotlin-runner:
    build:
      context: ./docker/runners/kotlin
      dockerfile: Dockerfile
    image: sandbox-kotlin-runner:latest
    profiles:
      - runners

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sandbox-backend
    ports:
      - "8080:8080"
    environment:
      SANDBOX_CONTAINER_ROOT: /sandbox
      SANDBOX_HOST_ROOT: C:/Users/ivang/sandbox-runner/sandbox
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: sandbox
      DB_USER: sandbox
      DB_PASSWORD: sandbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/sandbox
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: sandbox-postgres
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
    ports:
      - "5432:5432"
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandbox -d sandbox"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sandbox-redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sandbox-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SANDBOX_CONTAINER_ROOT: /sandbox
      SANDBOX_HOST_ROOT: C:/Users/ivang/sandbox-runner/sandbox
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: sandbox
      DB_USER: sandbox
      DB_PASSWORD: sandbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/sandbox
    command: [ "bin/sandbox-worker", "com.ivan.sandbox.app.WorkerApplicationKt" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: sandbox-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: sandbox-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - sandbox-grafana-data:/var/lib/grafana

volumes:
  sandbox-postgres-data:
  sandbox-grafana-data: