ALTER TABLE code_runs
ADD COLUMN queued_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN started_at TIMESTAMP NULL,
ADD COLUMN finished_at TIMESTAMP NULL,
ADD COLUMN worker_id VARCHAR(100) NULL,
ADD COLUMN retry_count INT NOT NULL DEFAULT 0;